# general settings
name: SMID
model_type: ImageCleanModel
scale: 1
num_gpu: 1
manual_seed: 100
use_amp: true

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_SMIDImage
    random_reverse: true
    border_mode: false
    dataroot_gt: data/SMID/SMID_Long_np
    dataroot_lq: data/SMID/SMID_LQ_np
    train_size: [960, 512]
    cache_keys: ~
    cache_data: true
    padding: new_info

    filename_tmpl: "{}"
    io_backend:
      type: disk

    N_frames: 5
    use_flip: true
    use_rot: true
    color: RGB

    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1

    mini_batch_sizes: [1]
    iters: [300000]
    gt_size: 64
    gt_sizes: [64] 

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_SMIDImage
    dataroot_gt: data/SMID/SMID_Long_np
    dataroot_lq: data/SMID/SMID_LQ_np
    cache_data: true
    N_frames: 5
    padding: new_info
    train_size: [960, 512]

    io_backend:
      type: disk

# network structures
network_g:
  type: MultiModalRetinexFormer
  in_channels: 3
  out_channels: 3
  n_feat: 40
  stage: 2
  num_blocks: [1, 2, 2]

  fusion_type: gate # Options: 'gate' (adaptive gating), 'concat', 'add'

  # Luminance modality configuration
  modalities:
    depth:
      enabled: true
      encoder: vitb
      checkpoint: Depth-Anything-V2/checkpoints/depth_anything_v2_vitb.pth
      freeze: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 300000
  warmup_iter: -1
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000]
    restart_weights: [1, 1]
    eta_mins: [0.0003, 0.000001]

  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 2e-4
    betas: [0.9, 0.999]

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 4
  val_freq: !!float 4e3
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: low_light
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
